name: Build PHP NDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm64-v8a:
    name: Build PHP arm64-v8a
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for cross-compilation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PHP Docker image
        run: |
          docker build \
            --build-arg TARGET=aarch64-linux-android \
            --build-arg API_LEVEL=32 \
            --build-arg PHP_VERSION=8.4.2 \
            --target buildsystem \
            --tag php-ndk-arm64-v8a \
            .
          
      - name: Verify build
        run: docker run --rm php-ndk-arm64-v8a php -v
