name: Build and Release NDK Artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_package:
    strategy:
      matrix:
        architecture:
          - abi: "armeabi-v7a"
            target: "armv7a-linux-androideabi32"
          - abi: "arm64-v8a"
            target: "aarch64-linux-android" # <-- This is your aarch64 target!

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build PHP/SQLite for ${{ matrix.architecture.abi }}
        id: build-docker-target
        run: |
          docker build \
            --target buildsystem \
            --tag php-ndk-builder:${{ matrix.architecture.abi }} \
            --build-arg NDK_TARGET="${{ matrix.architecture.target }}" \
            .
      - name: Create Artifact Directory
        id: create-dir
        run: |
          mkdir -p release-package/binaries/${{ matrix.architecture.abi }}
          mkdir -p release-package/includes/php # Headers are architecture-agnostic
          if [ ! -d "release-package/includes/php" ]; then
             mkdir -p release-package/includes/php
          fi

      - name: Extract Compiled Binaries and Headers
        id: extract
        run: |
          CONTAINER_ID=$(docker create php-ndk-builder:${{ matrix.architecture.abi }})
          
          docker cp $CONTAINER_ID:/root/install/. ./release-package/binaries/${{ matrix.architecture.abi }}
          
          if [ "${{ matrix.architecture.abi }}" == "armeabi-v7a" ]; then
             docker cp $CONTAINER_ID:/root/php-8.4.2/. ./release-package/includes/php
          fi
          
          docker rm $CONTAINER_ID

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-ndk-artifacts-${{ matrix.architecture.abi }}
          path: release-package/binaries/${{ matrix.architecture.abi }}
          if-no-files-found: ignore


  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Download all ABI artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-package/binaries

      - name: Prepare Final Directory Structure
        run: |
          mkdir -p ./php-ndk-artifacts/lib/arm64-v8a
          mkdir -p ./php-ndk-artifacts/lib/armeabi-v7a
          mkdir -p ./php-ndk-artifacts/include

      - name: Move Binaries to Final Structure
        run: |
          mv ./release-package/binaries/php-ndk-artifacts-arm64-v8a/* ./php-ndk-artifacts/lib/arm64-v8a/
          mv ./release-package/binaries/php-ndk-artifacts-armeabi-v7a/* ./php-ndk-artifacts/lib/armeabi-v7a/

          docker build --target buildsystem --tag header-extractor --build-arg NDK_TARGET="aarch64-linux-android" .
          CONTAINER_ID=$(docker create header-extractor)
          docker cp $CONTAINER_ID:/root/php-8.4.2/. ./php-ndk-artifacts/include/php
          docker rm $CONTAINER_ID
          
          mv ./php-ndk-artifacts/lib/arm64-v8a/php.so ./php-ndk-artifacts/lib/arm64-v8a/libphp_sapi.so
          mv ./php-ndk-artifacts/lib/arm64-v8a/libsqlite3.so ./php-ndk-artifacts/lib/arm64-v8a/libsqlite3.so
          mv ./php-ndk-artifacts/lib/armeabi-v7a/php.so ./php-ndk-artifacts/lib/armeabi-v7a/libphp_sapi.so
          mv ./php-ndk-artifacts/lib/armeabi-v7a/libsqlite3.so ./php-ndk-artifacts/lib/armeabi-v7a/libsqlite3.so


      - name: Create ZIP Release Asset
        run: |
          zip -r php-ndk-artifacts.zip php-ndk-artifacts
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: php-ndk-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
