name: Docker Build and Release Asset

on:
  push:
    branches: 
      - master
      - main
  create:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # --- Build the Docker Image ---
    - name: Build Docker image and load to Docker daemon
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: php-ndk-image:latest 
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # --- Save the Image as a Tar Archive (CONDITIONAL) ---
    - name: Save Docker image as tar
      # CRITICAL FIX: Only run this step if the workflow was triggered by a tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker save php-ndk-image:latest -o php-ndk-image.tar

    # --- Upload the Tar Archive to the Release (CONDITIONAL) ---
    - name: Upload Release Asset
      id: upload-asset 
      # CRITICAL FIX: Only run this step if the workflow was triggered by a tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: php-ndk-image.tar 
        body: |
          Docker image archive for release ${{ github.ref_name }}.
