name: Build PHP Android (arm64-v8a)

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'
      - '*.patch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PHP for Android arm64-v8a
        run: |
          docker build \
            --build-arg TARGET=aarch64-linux-android \
            --build-arg API_LEVEL=32 \
            --build-arg PHP_VERSION=8.4.2 \
            --target buildsystem \
            -t php-ndk-arm64-v8a .

      - name: Extract build artifacts
        run: |
          docker create --name extract php-ndk-arm64-v8a
          docker cp extract:/root/build/install ./build-output
          docker rm extract
          ls -lah build-output

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-android-arm64-v8a
          path: build-output/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-android-arm64-v8a
          path: release-files/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}-php8.4.2-arm64
          name: "PHP Android arm64-v8a Build #${{ github.run_number }}"
          files: |
            release-files/php.so
            release-files/libsqlite3.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
