name: Docker Build and Release Asset

on:
  # This workflow should only run when you create a new Tag (which creates a Release)
  # Example: git tag v1.0.0; git push origin v1.0.0
  create:
    tags:
      - 'v*.*.*' # Runs on tags like v1.0.0, v2.1.5, etc.

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating a Release and uploading the asset
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # --- Build the Docker Image ---
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        # We don't push it, we just build it locally with a tag
        push: false
        tags: php-ndk-image:latest 

    # --- Save the Image as a Tar Archive ---
    - name: Save Docker image as tar
      run: |
        # Use 'docker save' to package the image into a file
        docker save php-ndk-image:latest -o php-ndk-image.tar

    # --- Upload the Tar Archive to the Release ---
    - name: Upload Release Asset
      id: upload-asset 
      uses: softprops/action-gh-release@v2
      with:
        # The tag from the 'create' event is automatically used for the release
        files: php-ndk-image.tar 
        # Add a placeholder for the release body if the tag doesn't have one
        body: |
          Docker image archive for release ${{ github.ref_name }}.
