name: Build and Release NDK Artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - abi: "arm64-v8a"
            target: "aarch64-linux-android32"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Build Stage ---
      - name: Build PHP + SQLite for ${{ matrix.architecture.abi }}
        run: |
          docker build \
            --build-arg TARGET=${{ matrix.architecture.target }} \
            --build-arg PHP_VERSION=8.4.2 \
            -t php-ndk-builder:${{ matrix.architecture.abi }} .

      # --- Extract Stage ---
      - name: Extract Binaries and Headers
        run: |
          mkdir -p release-package/binaries/${{ matrix.architecture.abi }}
          mkdir -p release-package/includes/php

          CONTAINER_ID=$(docker create php-ndk-builder:${{ matrix.architecture.abi }})
          docker cp $CONTAINER_ID:/artifacts/php.so ./release-package/binaries/${{ matrix.architecture.abi }}/libphp.so
          docker cp $CONTAINER_ID:/artifacts/libsqlite3.so ./release-package/binaries/${{ matrix.architecture.abi }}/libsqlite3.so
          docker cp $CONTAINER_ID:/artifacts/headers/php ./release-package/includes/php
          docker rm $CONTAINER_ID

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-ndk-artifacts-${{ matrix.architecture.abi }}
          path: release-package/
          if-no-files-found: error

  # --- Release Stage ---
  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: php-ndk-artifacts-arm64-v8a
          path: ./release-package

      - name: Prepare Final Directory
        run: |
          mkdir -p ./php-ndk-artifacts/lib/arm64-v8a
          mkdir -p ./php-ndk-artifacts/include/php

          mv ./release-package/binaries/arm64-v8a/libphp.so ./php-ndk-artifacts/lib/arm64-v8a/
          mv ./release-package/binaries/arm64-v8a/libsqlite3.so ./php-ndk-artifacts/lib/arm64-v8a/
          cp -r ./release-package/includes/php/* ./php-ndk-artifacts/include/php/

      - name: Create ZIP Archive
        run: zip -r php-ndk-artifacts.zip php-ndk-artifacts

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: php-ndk-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
