name: Build and Release NDK Artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_package:
    strategy:
      matrix:
        architecture:
          - abi: "armeabi-v7a"
            target: "armv7a-linux-androideabi32"
          - abi: "arm64-v8a"
            target: "aarch64-linux-android"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build PHP/SQLite for ${{ matrix.architecture.abi }}
        run: |
          docker build \
            --target buildsystem \
            --tag php-ndk-builder:${{ matrix.architecture.abi }} \
            --build-arg NDK_TARGET="${{ matrix.architecture.target }}" \
            .

      - name: Create ABI Directory
        run: |
          mkdir -p release-package/binaries/${{ matrix.architecture.abi }}
          if [ "${{ matrix.architecture.abi }}" == "armeabi-v7a" ]; then
            mkdir -p release-package/includes/php
          fi

      - name: Extract Binaries and Headers
        run: |
          CONTAINER_ID=$(docker create php-ndk-builder:${{ matrix.architecture.abi }})
          docker cp $CONTAINER_ID:/root/install/. ./release-package/binaries/${{ matrix.architecture.abi }}
          if [ "${{ matrix.architecture.abi }}" == "armeabi-v7a" ]; then
            docker cp $CONTAINER_ID:/root/php-8.4.2/. ./release-package/includes/php
          fi
          docker rm $CONTAINER_ID

      - uses: actions/upload-artifact@v4
        with:
          name: php-ndk-artifacts-${{ matrix.architecture.abi }}
          path: release-package/binaries/${{ matrix.architecture.abi }}
          if-no-files-found: ignore

  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Download all ABI artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-package/binaries

      - name: Prepare final structure and headers
        run: |
          mkdir -p ./php-ndk-artifacts/lib/arm64-v8a
          mkdir -p ./php-ndk-artifacts/lib/armeabi-v7a
          mkdir -p ./php-ndk-artifacts/include/php
          # Copy headers once from builder image
          docker build --target buildsystem --tag header-extractor --build-arg NDK_TARGET="aarch64-linux-android" .
          CONTAINER_ID=$(docker create header-extractor)
          docker cp $CONTAINER_ID:/root/php-8.4.2/. ./php-ndk-artifacts/include/php
          docker rm $CONTAINER_ID

      - name: Move binaries
        run: |
          mv ./release-package/binaries/armeabi-v7a/* ./php-ndk-artifacts/lib/armeabi-v7a/
          mv ./release-package/binaries/arm64-v8a/* ./php-ndk-artifacts/lib/arm64-v8a/
          mv ./php-ndk-artifacts/lib/armeabi-v7a/php.so ./php-ndk-artifacts/lib/armeabi-v7a/libphp_sapi.so
          mv ./php-ndk-artifacts/lib/arm64-v8a/php.so ./php-ndk-artifacts/lib/arm64-v8a/libphp_sapi.so

      - name: Create ZIP Release
        run: zip -r php-ndk-artifacts.zip php-ndk-artifacts

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: php-ndk-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
