name: Build and Release PHP NDK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a]
        target:
          armeabi-v7a: armv7a-linux-androideabi
          arm64-v8a: aarch64-linux-android

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build PHP + SQLite for ${{ matrix.abi }}
        run: |
          docker build \
            --build-arg TARGET=${{ matrix.target[matrix.abi] }} \
            --build-arg API_LEVEL=32 \
            --tag php-ndk-builder:${{ matrix.abi }} .

      - name: Extract Binaries and Headers
        run: |
          mkdir -p release-package/binaries/${{ matrix.abi }}
          if [ "${{ matrix.abi }}" == "armeabi-v7a" ]; then
            mkdir -p release-package/includes/php
          fi

          CONTAINER_ID=$(docker create php-ndk-builder:${{ matrix.abi }})
          docker cp $CONTAINER_ID:/root/build/install/. ./release-package/binaries/${{ matrix.abi }}
          
          if [ "${{ matrix.abi }}" == "armeabi-v7a" ]; then
            docker cp $CONTAINER_ID:/root/build/install/php-headers/. ./release-package/includes/php
          fi
          docker rm $CONTAINER_ID

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-ndk-artifacts-${{ matrix.abi }}
          path: release-package/binaries/${{ matrix.abi }}
          if-no-files-found: ignore

  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download ABI Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-package/binaries

      - name: Prepare Final Structure
        run: |
          mkdir -p php-ndk-artifacts/lib/armeabi-v7a
          mkdir -p php-ndk-artifacts/lib/arm64-v8a
          mkdir -p php-ndk-artifacts/include

          # Move binaries
          mv ./release-package/binaries/armeabi-v7a/* ./php-ndk-artifacts/lib/armeabi-v7a/
          mv ./release-package/binaries/arm64-v8a/* ./php-ndk-artifacts/lib/arm64-v8a/

          # Move headers from first ABI extraction
          mv ./release-package/includes/php ./php-ndk-artifacts/include/php

          # Rename PHP shared libs
          mv php-ndk-artifacts/lib/armeabi-v7a/php.so php-ndk-artifacts/lib/armeabi-v7a/libphp_sapi.so
          mv php-ndk-artifacts/lib/arm64-v8a/php.so php-ndk-artifacts/lib/arm64-v8a/libphp_sapi.so

      - name: Create ZIP Release Asset
        run: |
          zip -r php-ndk-artifacts.zip php-ndk-artifacts

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: php-ndk-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
