name: Build PHP NDK for arm64-v8a

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PHP and SQLite in Docker
        run: |
          docker build \
            --build-arg TARGET=aarch64-linux-android \
            --build-arg API_LEVEL=32 \
            --build-arg PHP_VERSION=8.4.2 \
            --target buildsystem \
            --tag php-ndk-arm64-v8a \
            .

      - name: Extract compiled binaries and headers
        run: |
          mkdir -p release-package/lib/arm64-v8a
          mkdir -p release-package/include/php

          CONTAINER_ID=$(docker create php-ndk-arm64-v8a)
          docker cp $CONTAINER_ID:/root/build/install/. ./release-package/lib/arm64-v8a
          docker cp $CONTAINER_ID:/root/build/install/php-headers/. ./release-package/include/php
          docker rm $CONTAINER_ID

      - name: Rename PHP binary
        run: |
          mv release-package/lib/arm64-v8a/php.so release-package/lib/arm64-v8a/libphp_sapi.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-ndk-arm64-v8a
          path: release-package
          if-no-files-found: ignore

  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ./release-package

      - name: Zip final artifacts
        run: |
          zip -r php-ndk-artifacts.zip release-package

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: php-ndk-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
