name: Build PHP for Android (ARM32 + ARM64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PHP using Dockerfile
        run: |
          echo "Building PHP for Android..."
          docker build -t php-ndk .
          CONTAINER_ID=$(docker create php-ndk)
          docker cp "$CONTAINER_ID:/root/install" ./install
          docker rm "$CONTAINER_ID"
          echo "=== Contents of /root/install ==="
          ls -R ./install || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-android-build
          path: ./install/*
