name: Build and Release NDK Artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - abi: armeabi-v7a
            target: armv7a-linux-androideabi32
          - abi: arm64-v8a
            target: aarch64-linux-android

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build PHP + SQLite for this ABI
      - name: Build PHP/SQLite
        run: |
          docker build \
            --target buildsystem \
            --build-arg TARGET=${{ matrix.target }} \
            -t php-ndk-builder:${{ matrix.abi }} .

      # Prepare local artifact directories
      - name: Create Artifact Directory
        run: |
          mkdir -p release-package/binaries/${{ matrix.abi }}
          if [ "${{ matrix.abi }}" == "armeabi-v7a" ]; then
            mkdir -p release-package/includes/php
          fi

      # Extract binaries + headers
      - name: Extract Artifacts
        run: |
          CONTAINER=$(docker create php-ndk-builder:${{ matrix.abi }})
          docker cp $CONTAINER:/root/build/install/. ./release-package/binaries/${{ matrix.abi }}
          if [ "${{ matrix.abi }}" == "armeabi-v7a" ]; then
            docker cp $CONTAINER:/root/build/install/php-headers/. ./release-package/includes/php
          fi
          docker rm $CONTAINER

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-ndk-artifacts-${{ matrix.abi }}
          path: release-package/binaries/${{ matrix.abi }}
          if-no-files-found: ignore

  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-package/binaries

      - name: Prepare Final Structure
        run: |
          mkdir -p ./php-ndk-artifacts/lib/arm64-v8a
          mkdir -p ./php-ndk-artifacts/lib/armeabi-v7a
          mkdir -p ./php-ndk-artifacts/include

          # Copy headers from the first ABI build (armeabi-v7a)
          cp -r release-package/includes/php ./php-ndk-artifacts/include/php

      - name: Move Binaries and Rename
        run: |
          mv ./release-package/binaries/armeabi-v7a/* ./php-ndk-artifacts/lib/armeabi-v7a/
          mv ./release-package/binaries/arm64-v8a/* ./php-ndk-artifacts/lib/arm64-v8a/
          mv ./php-ndk-artifacts/lib/armeabi-v7a/php.so ./php-ndk-artifacts/lib/armeabi-v7a/libphp_sapi.so
          mv ./php-ndk-artifacts/lib/arm64-v8a/php.so ./php-ndk-artifacts/lib/arm64-v8a/libphp_sapi.so

      - name: Create ZIP
        run: |
          zip -r php-ndk-artifacts.zip php-ndk-artifacts

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: php-ndk-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
